apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJUC9yK3dlYVBic1l3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TlRFd01qa3dPVFV4TURkYUZ3MHpOVEV3TWpjd09UVTJNRGRhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUN1Y015OWtPZFpVMEZWS3lYdDFtazgrK0VaREpRS25nMkcrVXFkZWE1WDZPQmNmTGczTHI5YmdqdW4KN2xNTmVyMm1jUTA2K1pGMjBNNWx6UWdUMVA3M0U4MU4rMzUzL0hJeDFyOWF1eWxnaEVHRTcwejRpOHpkd3pmNwppeklpTmZXTkhDek8xT1lJbmR2WVpRa3ZqdU4wcnB4Tm01VHVYdUxpL3hwV1ozSGsxTTQybGd3a0RZSXZseDRJCnU2ZzN0MUUwU0JXVWJwREVHc0RvbWhNcFFHVnhVMnFMdGR4YVdMKzl3d0wvaFZDS1d6UG1kYU0xelFiM094KzQKQXFHYkdrbDdSdDREYm9RY1B1a2NWRGM1Z3g4bFUxSGM2Z2pUOVlYN0VXQ2M5MVJUSlJLT09jQkxVSnhMOHloSwpnZzNZeDErK3JkZVNCSzZteXZ5dVZXS014eTk1QWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJURjJTVHN0OTJzZWNXRHJMcnpPZUxmd3o2VVhqQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQ2FYVXp3RWk5UgovVXFoMFZtWkYvREN5MVlvMi9LTlZWUEZCR1A3Yzl1UHl3YUtuRXIwYk9UdEpsQVk3bTdydFNDYzdZNTJmUUpuCmd5dG1KUGw1R3FxZDJDNE9uRGpMNVNEQUw5VTEyNXMwSFdwV0lYZnhtbkFOTzdkS3lWRTBQUmg0ZDVRWUZKenMKZmxqYUI3R1QyTVhBNzBkK2o4eGoxUlVnTkFMRWdKRkxXdUovcnZEY0tHV1l0eTlZbzI5U29vLzcrZnFibTYyRworUjZSN1hOUGwzbG0weWF3TFExeHJTS2NtVncrNGlodG1sanpNVHh3YURld2JCZkkvMFkyckZ3d29FOGorbVRSCmhvRjhuSnMxT3hRdXNwSGp3ZVpFeTczTUdoeHMvaXJKZUU1V0krVGg0cUdxR0l4d2dHeXBpdCt5dzU2cnZJZWcKV1RkbDhzZHk1VXNQCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://A4B355130B37DF9654E40C391EAF0D1A.gr7.us-east-1.eks.amazonaws.com
  name: arn:aws:eks:us-east-1:890742610918:cluster/Prod-cluster
contexts:
- context:
    cluster: arn:aws:eks:us-east-1:890742610918:cluster/Prod-cluster
    user: arn:aws:eks:us-east-1:890742610918:cluster/Prod-cluster
  name: arn:aws:eks:us-east-1:890742610918:cluster/Prod-cluster
current-context: arn:aws:eks:us-east-1:890742610918:cluster/Prod-cluster
kind: Config
preferences: {}
users:
- name: arn:aws:eks:us-east-1:890742610918:cluster/Prod-cluster
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - --region
      - us-east-1
      - eks
      - get-token
      - --cluster-name
      - Prod-cluster
      - --output
      - json
      command: aws
